"""Create Sofascore MatchesReports model

Revision ID: 1d7720ca7433
Revises: 1dac0f14e3c9
Create Date: 2023-08-09 15:19:41.937008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d7720ca7433"
down_revision: Union[str, None] = "1dac0f14e3c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

create_trigger = """
    CREATE TRIGGER tr_{table}_updated BEFORE UPDATE ON {schema}.{table}
    FOR EACH ROW EXECUTE PROCEDURE {schema}.refresh_updated_at();
    """


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches_reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("totalPass", sa.Integer(), nullable=True),
        sa.Column("accuratePass", sa.Integer(), nullable=True),
        sa.Column("totalLongBalls", sa.Integer(), nullable=True),
        sa.Column("accurateLongBalls", sa.Integer(), nullable=True),
        sa.Column("totalClearance", sa.Integer(), nullable=True),
        sa.Column("savedShotsFromInsideTheBox", sa.Integer(), nullable=True),
        sa.Column("saves", sa.Integer(), nullable=True),
        sa.Column("punches", sa.Integer(), nullable=True),
        sa.Column("minutesPlayed", sa.Integer(), nullable=True),
        sa.Column("touches", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("possessionLostCtrl", sa.Integer(), nullable=True),
        sa.Column("expectedGoals", sa.Float(), nullable=True),
        sa.Column("goalsPrevented", sa.Float(), nullable=True),
        sa.Column("ratingVersions_original", sa.Float(), nullable=True),
        sa.Column("ratingVersions_alternative", sa.Float(), nullable=True),
        sa.Column("aerialWon", sa.Integer(), nullable=True),
        sa.Column("duelLost", sa.Integer(), nullable=True),
        sa.Column("duelWon", sa.Integer(), nullable=True),
        sa.Column("challengeLost", sa.Integer(), nullable=True),
        sa.Column("totalContest", sa.Integer(), nullable=True),
        sa.Column("onTargetScoringAttempt", sa.Integer(), nullable=True),
        sa.Column("goals", sa.Integer(), nullable=True),
        sa.Column("totalTackle", sa.Integer(), nullable=True),
        sa.Column("keyPass", sa.Integer(), nullable=True),
        sa.Column("expectedAssists", sa.Float(), nullable=True),
        sa.Column("aerialLost", sa.Integer(), nullable=True),
        sa.Column("blockedScoringAttempt", sa.Integer(), nullable=True),
        sa.Column("outfielderBlock", sa.Integer(), nullable=True),
        sa.Column("interceptionWon", sa.Integer(), nullable=True),
        sa.Column("fouls", sa.Integer(), nullable=True),
        sa.Column("dispossessed", sa.Integer(), nullable=True),
        sa.Column("wasFouled", sa.Integer(), nullable=True),
        sa.Column("totalCross", sa.Integer(), nullable=True),
        sa.Column("wonContest", sa.Integer(), nullable=True),
        sa.Column("shotOffTarget", sa.Integer(), nullable=True),
        sa.Column("accurateCross", sa.Integer(), nullable=True),
        sa.Column("penaltyWon", sa.Integer(), nullable=True),
        sa.Column("totalOffside", sa.Integer(), nullable=True),
        sa.Column("bigChanceMissed", sa.Integer(), nullable=True),
        sa.Column("penaltyMiss", sa.Integer(), nullable=True),
        sa.Column("penaltyConceded", sa.Integer(), nullable=True),
        sa.Column("bigChanceCreated", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches_reports")),
        sa.UniqueConstraint("match_id", "player_id", name=op.f("uq_matches_reports")),
        schema="sofascore",
    )
    op.execute(sa.text(create_trigger.format(schema="sofascore", table="matches_reports")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches_reports", schema="sofascore")
    # ### end Alembic commands ###
