"""Create FBRefScoutingReports model

Revision ID: 4b612e8fbe29
Revises: 2e24f34ca57e
Create Date: 2024-01-25 23:39:29.780617

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b612e8fbe29"
down_revision: Union[str, None] = "2e24f34ca57e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

create_trigger = """
    CREATE TRIGGER tr_{table}_updated BEFORE UPDATE ON {schema}.{table}
    FOR EACH ROW EXECUTE PROCEDURE {schema}.refresh_updated_at();
    """


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scouting_reports",
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("minutes_played", sa.Integer(), nullable=True),
        sa.Column("goals", sa.REAL(), nullable=True),
        sa.Column("assists", sa.REAL(), nullable=True),
        sa.Column("goals_plus_assists", sa.REAL(), nullable=True),
        sa.Column("non_penalty_goals", sa.REAL(), nullable=True),
        sa.Column("penalty_kicks_made", sa.REAL(), nullable=True),
        sa.Column("penalty_kicks_attempted", sa.REAL(), nullable=True),
        sa.Column("yellow_cards", sa.REAL(), nullable=True),
        sa.Column("red_cards", sa.REAL(), nullable=True),
        sa.Column("xg_expected_goals", sa.REAL(), nullable=True),
        sa.Column("npxg_non_penalty_xg", sa.REAL(), nullable=True),
        sa.Column("xag_expected_assisted_goals", sa.REAL(), nullable=True),
        sa.Column("npxg_plus_xag", sa.REAL(), nullable=True),
        sa.Column("progressive_carries", sa.REAL(), nullable=True),
        sa.Column("progressive_passes", sa.REAL(), nullable=True),
        sa.Column("progressive_passes_rec", sa.REAL(), nullable=True),
        sa.Column("shots_total", sa.REAL(), nullable=True),
        sa.Column("shots_on_target", sa.REAL(), nullable=True),
        sa.Column("shots_on_target_pct", sa.REAL(), nullable=True),
        sa.Column("goals_per_shot", sa.REAL(), nullable=True),
        sa.Column("goals_per_shot_on_target", sa.REAL(), nullable=True),
        sa.Column("average_shot_distance", sa.REAL(), nullable=True),
        sa.Column("shots_from_free_kicks", sa.REAL(), nullable=True),
        sa.Column("npxg_per_shot", sa.REAL(), nullable=True),
        sa.Column("goals_xg", sa.REAL(), nullable=True),
        sa.Column("non_penalty_goals_npxg", sa.REAL(), nullable=True),
        sa.Column("passes_completed", sa.REAL(), nullable=True),
        sa.Column("passes_attempted", sa.REAL(), nullable=True),
        sa.Column("pass_completion_pct", sa.REAL(), nullable=True),
        sa.Column("total_passing_distance", sa.REAL(), nullable=True),
        sa.Column("progressive_passing_distance", sa.REAL(), nullable=True),
        sa.Column("passes_completed_short", sa.REAL(), nullable=True),
        sa.Column("passes_attempted_short", sa.REAL(), nullable=True),
        sa.Column("pass_completion_pct_short", sa.REAL(), nullable=True),
        sa.Column("passes_completed_medium", sa.REAL(), nullable=True),
        sa.Column("passes_attempted_medium", sa.REAL(), nullable=True),
        sa.Column("pass_completion_pct_medium", sa.REAL(), nullable=True),
        sa.Column("passes_completed_long", sa.REAL(), nullable=True),
        sa.Column("passes_attempted_long", sa.REAL(), nullable=True),
        sa.Column("pass_completion_pct_long", sa.REAL(), nullable=True),
        sa.Column("xa_expected_assists", sa.REAL(), nullable=True),
        sa.Column("key_passes", sa.REAL(), nullable=True),
        sa.Column("passes_into_final_third", sa.REAL(), nullable=True),
        sa.Column("passes_into_penalty_area", sa.REAL(), nullable=True),
        sa.Column("crosses_into_penalty_area", sa.REAL(), nullable=True),
        sa.Column("live_ball_passes", sa.REAL(), nullable=True),
        sa.Column("dead_ball_passes", sa.REAL(), nullable=True),
        sa.Column("passes_from_free_kicks", sa.REAL(), nullable=True),
        sa.Column("through_balls", sa.REAL(), nullable=True),
        sa.Column("switches", sa.REAL(), nullable=True),
        sa.Column("crosses", sa.REAL(), nullable=True),
        sa.Column("throw_ins_taken", sa.REAL(), nullable=True),
        sa.Column("corner_kicks", sa.REAL(), nullable=True),
        sa.Column("inswinging_corner_kicks", sa.REAL(), nullable=True),
        sa.Column("outswinging_corner_kicks", sa.REAL(), nullable=True),
        sa.Column("straight_corner_kicks", sa.REAL(), nullable=True),
        sa.Column("passes_offside", sa.REAL(), nullable=True),
        sa.Column("passes_blocked", sa.REAL(), nullable=True),
        sa.Column("shot_creating_actions", sa.REAL(), nullable=True),
        sa.Column("sca_live_ball_pass", sa.REAL(), nullable=True),
        sa.Column("sca_dead_ball_pass", sa.REAL(), nullable=True),
        sa.Column("sca_take_on", sa.REAL(), nullable=True),
        sa.Column("sca_shot", sa.REAL(), nullable=True),
        sa.Column("sca_fouls_drawn", sa.REAL(), nullable=True),
        sa.Column("sca_defensive_action", sa.REAL(), nullable=True),
        sa.Column("goal_creating_actions", sa.REAL(), nullable=True),
        sa.Column("gca_live_ball_pass", sa.REAL(), nullable=True),
        sa.Column("gca_dead_ball_pass", sa.REAL(), nullable=True),
        sa.Column("gca_take_on", sa.REAL(), nullable=True),
        sa.Column("gca_shot", sa.REAL(), nullable=True),
        sa.Column("gca_fouls_drawn", sa.REAL(), nullable=True),
        sa.Column("gca_defensive_action", sa.REAL(), nullable=True),
        sa.Column("tackles", sa.REAL(), nullable=True),
        sa.Column("tackles_won", sa.REAL(), nullable=True),
        sa.Column("tackles_def_3rd", sa.REAL(), nullable=True),
        sa.Column("tackles_mid_3rd", sa.REAL(), nullable=True),
        sa.Column("tackles_att_3rd", sa.REAL(), nullable=True),
        sa.Column("dribblers_tackled", sa.REAL(), nullable=True),
        sa.Column("dribbles_challenged", sa.REAL(), nullable=True),
        sa.Column("pct_of_dribblers_tackled", sa.REAL(), nullable=True),
        sa.Column("challenges_lost", sa.REAL(), nullable=True),
        sa.Column("blocks", sa.REAL(), nullable=True),
        sa.Column("shots_blocked", sa.REAL(), nullable=True),
        sa.Column("interceptions", sa.REAL(), nullable=True),
        sa.Column("tkl_plus_int", sa.REAL(), nullable=True),
        sa.Column("clearances", sa.REAL(), nullable=True),
        sa.Column("errors", sa.REAL(), nullable=True),
        sa.Column("touches", sa.REAL(), nullable=True),
        sa.Column("touches_def_pen", sa.REAL(), nullable=True),
        sa.Column("touches_def_3rd", sa.REAL(), nullable=True),
        sa.Column("touches_mid_3rd", sa.REAL(), nullable=True),
        sa.Column("touches_att_3rd", sa.REAL(), nullable=True),
        sa.Column("touches_att_pen", sa.REAL(), nullable=True),
        sa.Column("touches_live_ball", sa.REAL(), nullable=True),
        sa.Column("take_ons_attempted", sa.REAL(), nullable=True),
        sa.Column("successful_take_ons", sa.REAL(), nullable=True),
        sa.Column("successful_take_on_pct", sa.REAL(), nullable=True),
        sa.Column("times_tackled_during_take_on", sa.REAL(), nullable=True),
        sa.Column("tackled_during_take_on_pct", sa.REAL(), nullable=True),
        sa.Column("carries", sa.REAL(), nullable=True),
        sa.Column("total_carrying_distance", sa.REAL(), nullable=True),
        sa.Column("progressive_carrying_distance", sa.REAL(), nullable=True),
        sa.Column("carries_into_final_third", sa.REAL(), nullable=True),
        sa.Column("carries_into_penalty_area", sa.REAL(), nullable=True),
        sa.Column("miscontrols", sa.REAL(), nullable=True),
        sa.Column("dispossessed", sa.REAL(), nullable=True),
        sa.Column("passes_received", sa.REAL(), nullable=True),
        sa.Column("second_yellow_card", sa.REAL(), nullable=True),
        sa.Column("fouls_committed", sa.REAL(), nullable=True),
        sa.Column("fouls_drawn", sa.REAL(), nullable=True),
        sa.Column("offsides", sa.REAL(), nullable=True),
        sa.Column("penalty_kicks_won", sa.REAL(), nullable=True),
        sa.Column("penalty_kicks_conceded", sa.REAL(), nullable=True),
        sa.Column("own_goals", sa.REAL(), nullable=True),
        sa.Column("ball_recoveries", sa.REAL(), nullable=True),
        sa.Column("aerials_won", sa.REAL(), nullable=True),
        sa.Column("aerials_lost", sa.REAL(), nullable=True),
        sa.Column("pct_of_aerials_won", sa.REAL(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_scouting_reports")),
        schema="fbref",
    )
    op.execute(sa.text(create_trigger.format(schema="fbref", table="scouting_reports")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scouting_reports", schema="fbref")
    # ### end Alembic commands ###
