"""Register trg_market_value_refresh_updated_at

Revision ID: 46e091864030
Revises: fa8da4e31597
Create Date: 2024-04-27 18:00:06.828117

"""

from typing import Sequence, Union

from alembic_utils.pg_trigger import PGTrigger

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46e091864030"
down_revision: Union[str, None] = "fa8da4e31597"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    transfermarkt_market_value_trg_market_value_refresh_updated_at = PGTrigger(
        schema="transfermarkt",
        signature="trg_market_value_refresh_updated_at",
        on_entity="transfermarkt.market_value",
        is_constraint=False,
        definition=(
            "BEFORE UPDATE ON transfermarkt.market_value FOR EACH ROW EXECUTE FUNCTION public.refresh_updated_at()"
        ),
    )
    op.create_entity(transfermarkt_market_value_trg_market_value_refresh_updated_at)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    transfermarkt_market_value_trg_market_value_refresh_updated_at = PGTrigger(
        schema="transfermarkt",
        signature="trg_market_value_refresh_updated_at",
        on_entity="transfermarkt.market_value",
        is_constraint=False,
        definition=(
            "BEFORE UPDATE ON transfermarkt.market_value FOR EACH ROW EXECUTE FUNCTION public.refresh_updated_at()"
        ),
    )
    op.drop_entity(transfermarkt_market_value_trg_market_value_refresh_updated_at)
    # ### end Alembic commands ###
