"""Register trg_seasons_refresh_updated_at

Revision ID: 69ab909bddb9
Revises: 1fc6a318af0d
Create Date: 2024-04-26 23:31:20.094329

"""

from typing import Sequence, Union

from alembic_utils.pg_trigger import PGTrigger

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69ab909bddb9"
down_revision: Union[str, None] = "1fc6a318af0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sofascore_seasons_trg_seasons_refresh_updated_at = PGTrigger(
        schema="sofascore",
        signature="trg_seasons_refresh_updated_at",
        on_entity="sofascore.seasons",
        is_constraint=False,
        definition="BEFORE UPDATE ON sofascore.seasons FOR EACH ROW EXECUTE FUNCTION public.refresh_updated_at()",
    )
    op.create_entity(sofascore_seasons_trg_seasons_refresh_updated_at)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sofascore_seasons_trg_seasons_refresh_updated_at = PGTrigger(
        schema="sofascore",
        signature="trg_seasons_refresh_updated_at",
        on_entity="sofascore.seasons",
        is_constraint=False,
        definition="BEFORE UPDATE ON sofascore.seasons FOR EACH ROW EXECUTE FUNCTION public.refresh_updated_at()",
    )
    op.drop_entity(sofascore_seasons_trg_seasons_refresh_updated_at)
    # ### end Alembic commands ###
