"""Register trg_tournaments_refresh_updated_at

Revision ID: 46a1eddcbc0e
Revises: 20683393b9b7
Create Date: 2024-04-26 23:58:33.539463

"""

from typing import Sequence, Union

from alembic_utils.pg_trigger import PGTrigger

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46a1eddcbc0e"
down_revision: Union[str, None] = "20683393b9b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sofascore_tournaments_trg_tournaments_refresh_updated_at = PGTrigger(
        schema="sofascore",
        signature="trg_tournaments_refresh_updated_at",
        on_entity="sofascore.tournaments",
        is_constraint=False,
        definition="BEFORE UPDATE ON sofascore.tournaments FOR EACH ROW EXECUTE FUNCTION public.refresh_updated_at()",
    )
    op.create_entity(sofascore_tournaments_trg_tournaments_refresh_updated_at)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sofascore_tournaments_trg_tournaments_refresh_updated_at = PGTrigger(
        schema="sofascore",
        signature="trg_tournaments_refresh_updated_at",
        on_entity="sofascore.tournaments",
        is_constraint=False,
        definition="BEFORE UPDATE ON sofascore.tournaments FOR EACH ROW EXECUTE FUNCTION public.refresh_updated_at()",
    )
    op.drop_entity(sofascore_tournaments_trg_tournaments_refresh_updated_at)
    # ### end Alembic commands ###
